In [ ]:
from chalk.client import ChalkClient
from chalk import _
from src.models import User, Transaction

In [ ]:
client = ChalkClient(branch="main")

## Online queries from code

In [ ]:
client.query(
    input={User.id: 1},
    output=[
        User,
        User.credit_report.percent_past_due,
    ],
    staleness={
        User.credit_report.percent_past_due: "0s",
    }
)

## Offline queries

In [15]:
client.offline_query(
    output=[
        User.name,
        User.denylisted,
        User.name_email_match_score,
        User.domain_name,
        User.email_username,
        User.total_spend,
        User.credit_report.percent_past_due,
    ],
    recompute_features=[User.credit_report.percent_past_due],
    max_samples=30,
).to_pandas()

,user.name,user.id,user.credit_report.percent_past_due,user.credit_report.id,user.total_spend,user.denylisted,user.name_email_match_score,user.domain_name,user.email_username
0,Nicole Mann,1,0.0,123,5239.06,False,75.000000,nasa.gov,nicoleam
1,Monica Geller,2,0.0,123,0.00,False,76.923077,yahoo.com,monica.geller.3299
2,Jackson Garter,3,0.0,123,0.00,False,66.666667,gmail.com,jackson3388
3,Emily Carter,4,0.0,123,0.00,False,75.000000,gmail.com,emily_carter21
4,Robert Johnson,5,0.0,123,0.00,False,81.481481,gmail.com,robertjohnson45
5,Sophia Lee,6,0.0,123,0.00,False,73.684211,gmail.com,sophialee88
6,Michael Brown,7,0.0,123,0.00,False,80.000000,gmail.com,michaelbrown56
7,Olivia Martinez,8,0.0,123,0.00,False,82.758621,gmail.com,oliviamartinez99
8,William Davis,9,0.0,123,0.00,False,80.000000,gmail.com,williamdavis77
9,Ava Wilson,10,0.0,123,0.00,False,73.684211,gmail.com,avawilson33
10,James Anderson,11,0.0,123,0.00,False,81.481481,gmail.com,jamesanderson11
11,Mia Thompson,12,0.0,123,0.00,False,78.260870,gmail.com,miathompson29
12,Benjamin Moore,13,0.0,123,0.00,False,81.481481,gmail.com,benjaminmoore65
13,Charlotte Hall,14,0.0,123,0.00,False,81.481481,gmail.com,charlottehall14
14,Lucas Allen,15,0.0,123,0.00,False,76.190476,gmail.com,lucasallen52
15,Harper White,16,0.0,123,0.00,False,78.260870,gmail.com,harperwhite99
16,Henry Scott,17,0.0,123,0.00,False,76.190476,gmail.com,henryscott88
17,Amelia Young,18,0.0,123,0.00,False,78.260870,gmail.com,ameliayoung77
18,Alexander King,19,0.0,123,0.00,False,81.481481,gmail.com,alexanderking45
19,Evelyn Green,20,0.0,123,0.00,False,78.260870,gmail.com,evelyngreen33
20,Daniel Nelson,21,0.0,123,0.00,False,80.000000,gmail.com,danielnelson22
21,Ella Carter,22,0.0,123,0.00,False,76.190476,gmail.com,ellacarter12
22,Matthew Baker,23,0.0,123,0.00,False,80.000000,gmail.com,matthewbaker79
23,Scarlett Adams,24,0.0,123,0.00,False,81.481481,gmail.com,scarlettadams55
24,David Phillips,25,0.0,123,0.00,False,81.481481,gmail.com,davidphillips43
25,Victoria Turner,26,0.0,123,0.00,False,82.758621,gmail.com,victoriaturner66
26,Joseph Walker,27,0.0,123,0.00,False,80.000000,gmail.com,josephwalker31
27,Grace Harris,28,0.0,123,0.00,False,78.260870,gmail.com,graceharris29
28,Andrew Collins,29,0.0,123,0.00,False,81.481481,gmail.com,andrewcollins99
29,Zoey Stewart,30,0.0,123,0.00,False,78.260870,gmail.com,zoeystewart76

In [ ]:
client.offline_query(
    max_samples=100,
    output=[
        Transaction.memo,
        Transaction.user_id,
        Transaction.amount
    ],
    recompute_features=True
).to_pandas()